# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab26ef83fc13cecec1e9254a6b57f529feedff73bb6912d846eb2f96ac689297d168052bedebf12aab30c838defbab683450de05fd20dae4b2bf90425d73549f

test:
  secret_key_base: ae39b419ce43d4b4b3357ca22caee8367e37294ba2836366aa902fc4867498d08f39a0760a346aa599c55892cb8ccc5eef7c9d6dd68d86127e0719b257af6170

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
